import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import test from 'node:test';
import { createOrGetActiveJob, getJobById } from '../../src/db/jobs.js';
import { pool } from '../../src/db/pool.js';
import { createRepo, getRepoBySlug } from '../../src/db/repos.js';
import { canonicalizeGitHubUrl } from '../../src/lib/github.js';
import { startWorker } from '../../src/review/worker.js';
import { buildServer } from '../../src/server.js';
import type { HealthStatus, ReviewJob, ReviewerSettings } from '../../src/types.js';

const fixtureUrl = process.env.TASK4_REPOSITORY_URL;
const OLLAMA_MARKER = 'Persisted local Ollama narrative marker.';

async function waitForJob(id: string): Promise<ReviewJob> {
  const deadline = Date.now() + 240_000;
  let job = await getJobById(id);
  while (job && (job.status === 'queued' || job.status === 'running') && Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, 250));
    job = await getJobById(id);
  }
  assert.ok(job);
  return job;
}

test('settings, health, Ollama persistence, and disabled fallback work end to end', { skip: !fixtureUrl }, async () => {
  const prompts: string[] = [];
  const ollama = createServer((request, response) => {
    if (request.method === 'GET' && request.url === '/api/tags') {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ models: [{ name: 'fixture-model' }] }));
      return;
    }
    if (request.method === 'POST' && request.url === '/api/generate') {
      let body = '';
      request.setEncoding('utf8');
      request.on('data', (chunk) => {
        body += chunk;
      });
      request.on('end', () => {
        prompts.push(body);
        response.writeHead(200, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ response: JSON.stringify({
          aiSummary: OLLAMA_MARKER,
          strengths: ['The local narrative preserved deterministic evidence.'],
          improvements: ['Keep the review evidence current.'],
          nextSteps: ['Rerun after the next meaningful change.'],
          portfolioBlurb: 'A locally narrated portfolio review.',
          portfolioFooter: 'Generated by the configured local model.',
        }) }));
      });
      return;
    }
    response.writeHead(404).end();
  });
  await new Promise<void>((resolve) => ollama.listen(0, '127.0.0.1', resolve));
  const address = ollama.address();
  assert.ok(address && typeof address === 'object');
  const baseUrl = `http://127.0.0.1:${address.port}`;

  const github = canonicalizeGitHubUrl(fixtureUrl ?? '');
  await pool.query('DELETE FROM repos WHERE slug = ?', [github.slug]);
  const app = await buildServer({ logger: false });
  startWorker(app);
  try {
    const saved = await app.inject({
      method: 'PUT',
      url: '/api/settings',
      payload: { ollamaBaseUrl: baseUrl, ollamaModel: 'fixture-model' },
    });
    assert.equal(saved.statusCode, 200);
    assert.deepEqual(saved.json() as ReviewerSettings, { ollamaBaseUrl: baseUrl, ollamaModel: 'fixture-model' });
    assert.deepEqual((await app.inject({ method: 'GET', url: '/api/settings' })).json(), saved.json());

    const health = await app.inject({ method: 'GET', url: '/api/health' });
    assert.equal(health.statusCode, 200);
    const capability = health.json() as HealthStatus;
    assert.equal(capability.ollama.reachable, true);
    assert.equal(capability.ollama.model, 'fixture-model');
    assert.equal(JSON.stringify(capability).includes(baseUrl), false);

    const repository = await createRepo({
      slug: github.slug,
      name: 'Controlled Ollama Integration Fixture',
      url: github.canonicalUrl,
      canonicalUrl: github.canonicalUrl,
    });
    const queued = await createOrGetActiveJob(repository.id);
    assert.ok(queued);
    const completed = await waitForJob(queued.job.id);
    assert.equal(completed.status, 'succeeded', completed.error?.message ?? 'Ollama-backed job did not succeed.');
    const narrated = await getRepoBySlug(github.slug);
    assert.equal(narrated?.ai, OLLAMA_MARKER);
    assert.equal(prompts.length, 1);
    assert.ok(Buffer.byteLength(prompts[0] ?? '') < 20_000);
    assert.doesNotMatch(prompts[0] ?? '', /BEGIN .*PRIVATE KEY|gh[pousr]_[A-Za-z0-9]{30,}/);

    const disabled = await app.inject({
      method: 'PUT',
      url: '/api/settings',
      payload: { ollamaBaseUrl: '', ollamaModel: 'fixture-model' },
    });
    assert.equal(disabled.statusCode, 200);
    const rerun = await app.inject({ method: 'POST', url: `/api/repos/${github.slug}/rerun` });
    assert.equal(rerun.statusCode, 202);
    const fallbackJob = await waitForJob((rerun.json() as { jobId: string }).jobId);
    assert.equal(fallbackJob.status, 'succeeded', fallbackJob.error?.message ?? 'Fallback job did not succeed.');
    const fallback = await getRepoBySlug(github.slug);
    assert.ok(fallback?.ai);
    assert.notEqual(fallback.ai, OLLAMA_MARKER);
    assert.equal(prompts.length, 1);
  } finally {
    await app.close();
    await new Promise<void>((resolve, reject) => ollama.close((error) => error ? reject(error) : resolve()));
    await pool.end();
  }
});
